# Python Qualification Exam

## .../15 Q1. Mathematical Functions
#### .../5 1a. Define the function `P(a,x)` that returns $$\sum_{i=0}^n a_{i}x^{(n-i)}$$
#### Here, `a` is a list which contains `n+1` floating numbers inside; `x` is a floating number.
#### Hint: $a_{k}\equiv $ `a[k]` where k is an integer.
In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [81]:
def P(a,x):
    i=0
    n = len(a)
    result =0.0
    while i < n:
        result = result + (a[i] * (x**(n-1-i)))   
        i= i+1
    
    return result

#### Do not change this cell and test your code here.

In [82]:
P([0,1,-2,3],4)

11.0

#### .../2 1b. Define the function `fp(f,x)` which has two inputs `f, x` and returns the derivative $f^{'}(x)$
Here, f is a callable and differentiable mathemathical function(defined out of this function) at the point x with one float input, returns one float output

(i.e. $f(x)=x^2+4x-5$) and x is a floating number.

Hint: You may define the derivative as $f^{'}(x) = \frac{f(x+h)-f(x)}{h}$ where $h=10^{-6}$

In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [83]:
def fp(f,x):
    result = 0.0
    h = 1E-6
    result = (f(x+h)-f(x)) / h
    
    return result

#### Do not change this cell and test your code here.

In [84]:
fx = lambda x: 3*x**2 - 2*x**3 + 2.72**x - 9*x + 21
round(fp(fx,5))

20

#### .../8 1c. Define the function `fi(f,a,b)` has three inputs `f, a,b` and returns the integral

$$\int_{a}^{b} f(x) dx$$

#### with the trapezoidal rule.

Here, f is a callable mathemathical function that possible to integrate within the boundaries a and b.

a and b are floating numbers.

(i.e. $f(x)=x^2+4x-5$) and x is a floating number.

Hint: You may define the integral as:

${\int\limits_a^b {f\left( x \right)dx} \approx {T_n} }={ {\frac{{\Delta x}}{2}}\left[ {{f\left( {{x_0}} \right)} + {2f\left( {{x_1}} \right)} }\right.}+{\left.{ {2f\left( {{x_2}} \right)} + \cdots }\right.}+{\left.{ {2f\left( {{x_{n – 1}}} \right)} + {f\left( {{x_n}} \right)}} \right],}$
where $\Delta x = \large{\frac{{b – a}}{n}}\normalsize$ and ${x_i} = a + i\Delta x$.

You should find proper $n$ and $x_0$ values for this question.

In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [85]:
def fi(f,a,b):
    n = 9
    result = 0.0
    delta = (b-a) / n
    i = 0 
    while i < n:
        x = a + delta *i
        result = result + delta* f(x) 
        i = i + 1
        
    return result* (delta/2)

#### Do not change this cell and test your code here.

In [86]:
fx = lambda x: 3*x**2 + 2*x
round(fi(fx,3,5))

12

## .../20 Q2. NumPy, Pandas

#### .../6 2a. Define the function `array_oper(arr,operation)` where `arr` is a NumPy array and `operation` is a string.

#### If `operation` is `'square'`, return the array which has elements squares of `arr`.
#### If `operation` is `'squareroot'`, return the array which has elements square roots of `arr`.
#### If `operation` is `'summing'`, return sum of the elements of `arr`.
#### If `operation` is `'randomize'`, return a random array that has a shape of `arr` where the random numbers are between 1 and 4 (including 1 and 4).
#### If `operation` is `'create_zeros'`, return a zeros array that has a shape of `arr`.
#### If `operation` is anything else, return an array which has size of `arr` where all its numbers are 4.

In [87]:
import numpy as np
arr1 = np.array(([1,2,3],[4,5,6],[7,8,9],[1.5,2.5,3.5]))
arr2 = np.array(([1,2,3],[4,5,6],[7,8,9],[1.5,2.5,3.5]))
def array_oper(arr,operation):
    if operation == "square":
        i=0
        while i<4:
            arr1[i]= arr1[i]**2
            i=i+1
        return arr1
    elif operation == "squareroot":
        i=0
        while i<4:
            arr2[i]=arr2[i]**0.5
            i=i+1
        return arr2
    elif operation =="summing":
        result =0
        for i in arr:
            result = result + i
        return result
    elif operation == "randomize":
        return  np.random.randint(1,4, size = arr.shape)
    elif operation == "create_zeros":
        return np.zeros(arr.shape)
    else:
        return np.full(arr.shape, 4)

#### Do not change this cell and test your code here.

In [88]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9],[1.5,2.5,3.5]))
arr2 = array_oper(arr,'square')
arr3 = array_oper(arr2,'squareroot')
arr4 = arr3 - arr
arr5 = array_oper(arr,'create_zeros')
print(arr4)
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### .../2 2b. Read the csv file directly from URL (don't download it) as a Pandas DataFrame.
#### The name of the variable of this dataframe should be `df`.:
url = https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/639388c2cbc2120a14dcf466e85730eb8be498bb/iris.csv
#### Define the column names as:
`["sepal-length", "sepal-width", "petal-length", "petal-width", "target"]`

In [89]:
import pandas as pd


#### .../5 2c. Find the average values of the features `"sepal-length", "sepal-width", "petal-length", "petal-width",` for each unique value in the column 'target'.
#### Print the name of the unique value, feature name and the average value that you found one by one.
Hint: If you have found $n$ unique values in the column 'target', you should print $n \times 4$ lines.

In [90]:
df = pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/639388c2cbc2120a14dcf466e85730eb8be498bb/iris.csv")

#### .../7 2d. Create the columns `"sepal-ratio" and "petal-ratio"` which are the ratios of
#### `"sepal-length"/"sepal-width"`, `"petal-length"/"petal-width"` respectively for each row to the dataframe `df`.

In [91]:
df["sepal_ratio"]=df["sepal_length"] / df["sepal_width"]
df["petal_ratio"]=df["petal_length"] / df["petal_width"]

## .../30 Q3. File Reading, Text and List Operations

#### .../4 3a. Open the file asd.txt in read mode, make the computer read it and assign it to the variable `text`.
You will encounter the characters `\n`. Replace them with space.

Hint: The type of the variable `text` should be string.

In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [12]:
f = open("asd.txt","r")
text = f.read()
text = text.replace("\n"," ")

#### Do not change this cell and test your code here. It should give the stated output.

In [13]:
text

'Data science is an inter-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from structured and unstructured data.[1][2] Data science is related to data mining and big data.  Data science is a "concept to unify statistics, data analysis, machine learning and their related methods" in order to "understand and analyze actual phenomena" with data.[3] It employs techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, and information science. Turing award winner Jim Gray imagined data science as a "fourth paradigm" of science (empirical, theoretical, computational and now data-driven) and asserted that "everything about science is changing because of the impact of information technology" and the data deluge.[4][5] In 2015, the American Statistical Association identified database management, statistics and machine learning, and distributed and parallel systems as the thr

#### .../3 3b. Once you assigned the variable `text` correctly, define the function `textsplitter(text)`  which takes the string `text` 
#### and returns the list `textlist `having `text`'s words as its elements with lowercase characters.
#### Assume that all the words are only separated with a space, nothing else.

In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [14]:
def textsplitter(text):
    textlist = []
    textlist2 = []
    
   
    textlist = text.split()  
    for i in textlist:
        textlist2.append(i.lower())
        
    return textlist2

#### Do not change this cell and test your code here. It should give the stated output.

In [15]:
textlist = textsplitter(text)
textlist[:40]

['data',
 'science',
 'is',
 'an',
 'inter-disciplinary',
 'field',
 'that',
 'uses',
 'scientific',
 'methods,',
 'processes,',
 'algorithms',
 'and',
 'systems',
 'to',
 'extract',
 'knowledge',
 'and',
 'insights',
 'from',
 'structured',
 'and',
 'unstructured',
 'data.[1][2]',
 'data',
 'science',
 'is',
 'related',
 'to',
 'data',
 'mining',
 'and',
 'big',
 'data.',
 'data',
 'science',
 'is',
 'a',
 '"concept',
 'to']

#### .../6 3c. Define the function `bracketremover(txt)` where `txt` is a string. The function should remove all the box brackets and texts inside the brackets and return cleaned text.
Hint: you may either use the library `re` or write the function with a loop.

Examples: 
```python
>>>txt = 'science[2]'
>>>bracketremover(txt)
'science'

>>>txt2 = 'science[5](4)[1]'
>>>bracketremover(txt2)
'science(4)'

>>>txt3 = 'science[1]data[2]'
>>>bracketremover(txt3)
'sciencedata'
```

In [22]:
import re
def bracketremover(txt):
    pattern = r'\[[^\]]*\]'
    nt = re.sub(pattern, '', txt)
    return nt

#### Do not change this cell and test your code here. It should give the stated output.

In [23]:
removed = bracketremover('science[5](4)[1]')
removed

'science(4)'

#### .../4 3d. Define the function `textlist_converter(textlist)` that puts elements of `textlist` to the the function
#### `bracketremover` in a loop and returns the list `textlist_cleaned` which has no box brackets inside.
Hint: Create the empty list `textlist_cleaned`, append this list with `bracketremover(t)` for each `t` in textlist_cleaned.

In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [30]:
def textlist_converter(textlist):
    textlist_cleaned = []
    for i in textlist:
        textlist_cleaned.append(bracketremover(i))
    
    return textlist_cleaned

#### Do not change this cell and test your code here. It should give the stated output.

In [31]:
textlist_cleaned = textlist_converter(textlist)
textlist_cleaned[:40]

['data',
 'science',
 'is',
 'an',
 'inter-disciplinary',
 'field',
 'that',
 'uses',
 'scientific',
 'methods,',
 'processes,',
 'algorithms',
 'and',
 'systems',
 'to',
 'extract',
 'knowledge',
 'and',
 'insights',
 'from',
 'structured',
 'and',
 'unstructured',
 'data.',
 'data',
 'science',
 'is',
 'related',
 'to',
 'data',
 'mining',
 'and',
 'big',
 'data.',
 'data',
 'science',
 'is',
 'a',
 '"concept',
 'to']

#### .../3 3e. Define the function `unique_creator(textlist_cleaned)` that returns the list `textlist_unique` which has only
#### unique(no repeating) values of `textlist_cleaned`.
Hint: Look for sets.

In this question, you are only allowed to import and/or use Python's standard libraries in case you need. You are also allowed to use Python's default classes/functions.

In [33]:
def unique_creator(textlist_cleaned):
    textlist_unique = []
    for i in textlist_cleaned:
        if i not in textlist_unique:
            textlist_unique.append(i)
    
    return textlist_unique

#### Do not change this cell and test your code here.

In [34]:
textlist_unique = unique_creator(textlist_cleaned)
len(textlist_unique)

693

#### .../5 3f. Define the function `mapping(textlist_unique)` that returns the dictionary `textlist_map` which has the elements of
#### `textlist_unique` as keys and indicies of `textlist_unique` as values.
In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [51]:
def mapping(textlist_unique):
    textlist_map = dict()
    k =0
    for i in textlist_unique:
        textlist_map[i] = k
        k = k + 1
    return textlist_map

#### Do not change this cell and test your code here. It should give the stated output. (Orders could be different, no problem!)

In [52]:
textlist_map = mapping(textlist_unique)
textlist_map

{'data': 0,
 'science': 1,
 'is': 2,
 'an': 3,
 'inter-disciplinary': 4,
 'field': 5,
 'that': 6,
 'uses': 7,
 'scientific': 8,
 'methods,': 9,
 'processes,': 10,
 'algorithms': 11,
 'and': 12,
 'systems': 13,
 'to': 14,
 'extract': 15,
 'knowledge': 16,
 'insights': 17,
 'from': 18,
 'structured': 19,
 'unstructured': 20,
 'data.': 21,
 'related': 22,
 'mining': 23,
 'big': 24,
 'a': 25,
 '"concept': 26,
 'unify': 27,
 'statistics,': 28,
 'analysis,': 29,
 'machine': 30,
 'learning': 31,
 'their': 32,
 'methods"': 33,
 'in': 34,
 'order': 35,
 '"understand': 36,
 'analyze': 37,
 'actual': 38,
 'phenomena"': 39,
 'with': 40,
 'it': 41,
 'employs': 42,
 'techniques': 43,
 'theories': 44,
 'drawn': 45,
 'many': 46,
 'fields': 47,
 'within': 48,
 'the': 49,
 'context': 50,
 'of': 51,
 'mathematics,': 52,
 'computer': 53,
 'science,': 54,
 'information': 55,
 'science.': 56,
 'turing': 57,
 'award': 58,
 'winner': 59,
 'jim': 60,
 'gray': 61,
 'imagined': 62,
 'as': 63,
 '"fourth': 64,
 'p

#### .../4 3g. Define the function `list_to_vec(textlist_cleaned,textlist_map)` that returns the list  `textlist_vec`
#### which is the replaced form of `textlist_cleaned` with the mapping of `textlist_map`.
Hint: You may use a for loop and append the list  `textlist_vec` in each iteration.

Hint: `textlist_map[key]` gives the value of the dictionary.

In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [62]:
def list_to_vec(textlist_cleaned,textlist_map):
    textlist_vec = dict()
    k =0
    for i in textlist_cleaned:
        textlist_vec[i] =k
        k = k+1
    
    return textlist_vec

#### Do not change this cell and test your code here. It should give the stated output. (Orders could be different, no problem!)

In [64]:
textlist_vec = list_to_vec(textlist_cleaned,textlist_map)
textlist_vec


{'data': 1518,
 'science': 1520,
 'is': 1325,
 'an': 1425,
 'inter-disciplinary': 4,
 'field': 1408,
 'that': 1409,
 'uses': 736,
 'scientific': 1515,
 'methods,': 199,
 'processes,': 10,
 'algorithms': 11,
 'and': 1517,
 'systems': 136,
 'to': 1508,
 'extract': 15,
 'knowledge': 16,
 'insights': 18,
 'from': 1398,
 'structured': 20,
 'unstructured': 22,
 'data.': 1459,
 'related': 341,
 'mining': 927,
 'big': 1461,
 'a': 1365,
 '"concept': 38,
 'unify': 40,
 'statistics,': 74,
 'analysis,': 400,
 'machine': 130,
 'learning': 1397,
 'their': 1351,
 'methods"': 49,
 'in': 1511,
 'order': 51,
 '"understand': 53,
 'analyze': 55,
 'actual': 56,
 'phenomena"': 57,
 'with': 1088,
 'it': 1115,
 'employs': 1103,
 'techniques': 62,
 'theories': 1481,
 'drawn': 65,
 'many': 1369,
 'fields': 1213,
 'within': 69,
 'the': 1477,
 'context': 71,
 'of': 1503,
 'mathematics,': 73,
 'computer': 1131,
 'science,': 1422,
 'information': 677,
 'science.': 1093,
 'turing': 721,
 'award': 722,
 'winner': 723

#### .../3 3h. Define the function `joining(alist)` that joins all the elements of the list `alist` to a string with a space between all the elements.
Hint: You may use `alist = map(str, alist)` to convert all the non string elements of a list to strings.


In this question, you are only allowed to import and/or use Python's standard libraries in case you need. You are also allowed to use Python's default classes/functions.

In [92]:
def joining(alist):
    alist = map(str, alist)
    joined_str
    for i in alist :
        
    return joined_str
    

IndentationError: expected an indented block (<ipython-input-92-5cdec34d10a2>, line 6)

#### Do not change this cell and test your code here. It should give the obtained output. (Orders could be different, no problem!)

In [93]:
alist = [0,1,2,3]
joined_str = joinning(alist)
joined_str

NameError: name 'joinning' is not defined

## .../15 Q4. Object Oriented Programming
#### .../10 4.a Define the class `TextProcess()`. Define the initial function with the proper self variables. Put all the functions you defined in Q3
#### `textsplitter, bracketremover, textlist_converter, unique_creator, mapping, list_to_vec, joining` inside the class.
#### Define the function `converter(text)` inside the class which takes a string inside, runs all the functions by order and
#### returns mapped version of the string `text`.
In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

In [ ]:
class TextProcess:
    #your code here

#### Do not change this cell and test your code here. It should give the obtained output. (Orders could be different, no problem!)

In [ ]:
text_test = text
tp = TextProcess()
converted = tp.converter(text_test)
converted[:40]

#### .../5 4b. Write the variable `converted` to the file `output.txt`.
#### If you are not able to solve 4a., Write something else to the file `output.txt`
In this question, you are **not allowed** to import and/or use any library. You are allowed to use Python's default classes/functions unless you import anything.

#### Do not change this cell and test your code here. It should give the stated output.

In [ ]:
fread = open("output.txt", "r")
text_opened = fread.read()
text_opened == converted

## .../25 Q5. Probability and Statistics

#### .../4 5a. Define the function `flip_coin(n)` that simulates flipping a coin `n` times and returns an array of results.

#### The output array should only contain `1` and `0` where `1` indicated heads and `0` indicates tails.

#### e.g.
```python
>>>flip_coin(5)
[0,1,0,1,1]
```

In [99]:
import numpy as np
def flip_coin(n):
    return (np.random.randint(0,2,size=(n)))
    

#### Do not change this cell and test your code here.

In [100]:
flip_coin(10)


array([0, 1, 0, 1, 1, 0, 1, 1, 1, 1])

#### .../6 5b. Plot the graph `n` vs ratio of having heads for the closed interval [1,1000] by using the function `flip_coin(n)`.

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline


#### .../15 5c. Define the function `ball_prob(ball_box_dict, ball_draw_dict, n_draw, n_sim, replacement)` that simulates and returns the probability of drawing balls from a box.


#### `ball_box_dict` is the dictionary indicates how many balls are existing in the box from each color. (Keys of this dictionary is our sample space)

#### e.g. `ball_box_dict = {'red':8, 'blue':2, 'white':1, 'green':2}` means that there are 8 red, 2 blue, 1 white and 2 green balls in the box.

#### `ball_draw_dict` is the dictionary indicates how many balls we want to draw from each color to calculate probability.

#### `n_draw` is the integer number indicates how many balls are we drawing from the box.

#### `n_sim` is the integer number indicates how many times we are running the simulation.(Default: 10000)

#### `replacement` is the boolean value if we put the ball back to the box before drawing the other one or not.(Default: False)

#### Run the simulation `n_sim` times and calculate the probability for given values.

Hint, you can understand and test with the sample cases given below. Your probability should be close to those values:

e.g. Imagine a box that we have 5 blue, 2 purple and 6 red balls inside it. Calculate the probability of drawing exactly 2 red balls out of this box when we draw 5 balls at once(without replacement) by writing a simulation. Run the simulation 10000 times.

```python
>>>ball_box_dict={'blue':5,'purple':2,'red':6}
>>>ball_draw_dict={'red':2}
>>>n_draw=5
>>>n_sim=10000
>>>replacement=False
>>>ball_prob(ball_box_dict, ball_draw_dict, n_draw, n_sim, replacement)
0.41

```

e.g. Imagine a box that we have 5 blue, 8 black and 7 white balls inside it. Calculate the probability of drawing exactly 1 white ball and 2 black balls out of this box when we draw 3 balls at once(without replacement) by writing a simulation. Run the simulation 10000 times.

```python
>>>ball_box_dict={'blue':3,'black':8,'white':7}
>>>ball_draw_dict={'white':1,'black':2}
>>>n_draw=3
>>>n_sim=10000
>>>replacement=False
>>>ball_prob(ball_box_dict, ball_draw_dict, n_draw, n_sim, replacement)
0.24
```

e.g. Imagine a box that we have 5 blue, 8 black and 7 white balls inside it. We draw 3 balls one by one and putting the ball back to the box before drawing the next one(with replacement). Calculate the probability of drawing exactly 1 white ball and 2 black balls by writing a simulation. Run the simulation 10000 times.

```python
>>>ball_box_dict={'blue':3,'black':8,'white':7}
>>>ball_draw_dict={'white':1,'black':2}
>>>n_draw=3
>>>n_sim=10000
>>>replacement=True
>>>ball_prob(ball_box_dict, ball_draw_dict, n_draw, n_sim, replacement)
0.23
```

In [ ]:
import random
def ball_prob(ball_box_dict, ball_draw_dict, n_draw, n_sim=10000, replacement=False):
    #your code here

#### Do not change this cell and test your code here. It should give (nearly) the stated output.

In [ ]:
ball_box_dict={'black':3,'violet':8,'turquoise':7}
ball_draw_dict={'violet':2,'turquoise':1}
n_draw=3
n_sim=100000
replacement=True
ball_prob(ball_box_dict, ball_draw_dict, n_draw, n_sim, replacement)