In [1]:
mylist = [1,2,3]

In [2]:
mylist

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list =[[1,2,3],[4,5,5],[6,7,8]]

In [7]:
arr2= np.array(data_list)

In [8]:
arr2

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8]])

In [9]:
arr2[0][0]

1

In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [13]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [17]:
np.random.randint(0,100) 

88

In [19]:
 np.random.randint(10)

4

In [20]:
np.random.randint(0,100,5)

array([39, 27, 15,  9, 51])

In [21]:
np.random.rand(5)

array([0.83397657, 0.92623909, 0.85071744, 0.347518  , 0.26062145])

In [22]:
np.random.randn(5)

array([ 0.36576489, -1.41317265,  0.03849987,  1.13038739, -0.27717072])

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
newarray = np.random.randint(1,100,10)

In [30]:
newarray


array([29, 80, 50,  7, 59, 11, 18, 50, 41, 36])

In [31]:
newarray.max()

80

In [32]:
newarray.shape

(10,)

In [33]:
arr.shape

(25,)

In [34]:
data_list.shape

AttributeError: 'list' object has no attribute 'shape'

In [35]:
arr2.shape

(3, 3)